# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/ahmed98/Desktop/MS3/MS3.cache/wt [current_project]
set_property parent.project_path C:/Users/ahmed98/Desktop/MS3/MS3.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys-a7-100t:part0:1.0 [current_project]
set_property ip_output_repo c:/Users/ahmed98/Desktop/MS3/MS3.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/ahmed98/Desktop/MS3/MS3.srcs/sources_1/new/DFlipFlop.v
  C:/Users/ahmed98/Desktop/MS3/MS3.srcs/sources_1/new/MUX2.v
  C:/Users/ahmed98/Desktop/MS3/MS3.srcs/sources_1/new/FA.v
  C:/Users/ahmed98/Desktop/MS3/MS3.srcs/sources_1/new/MUX32_2.v
  C:/Users/ahmed98/Desktop/MS3/MS3.srcs/sources_1/new/reg32.v
  C:/Users/ahmed98/Desktop/MS3/MS3.srcs/sources_1/new/right_shifter.v
  C:/Users/ahmed98/Desktop/MS3/MS3.srcs/sources_1/new/defines.v
  C:/Users/ahmed98/Desktop/MS3/MS3.srcs/sources_1/new/Memory.v
  C:/Users/ahmed98/Desktop/MS3/MS3.srcs/sources_1/new/compressed_unit.v
  C:/Users/ahmed98/Desktop/MS3/MS3.srcs/sources_1/new/ALU32.v
  C:/Users/ahmed98/Desktop/MS3/MS3.srcs/sources_1/new/ALU_ctrlUnit.v
  C:/Users/ahmed98/Desktop/MS3/MS3.srcs/sources_1/new/BranchUnit.v
  C:/Users/ahmed98/Desktop/MS3/MS3.srcs/sources_1/new/ImmGen.v
  C:/Users/ahmed98/Desktop/MS3/MS3.srcs/sources_1/new/MUX32_4.v
  C:/Users/ahmed98/Desktop/MS3/MS3.srcs/sources_1/new/RCA32.v
  C:/Users/ahmed98/Desktop/MS3/MS3.srcs/sources_1/new/RegFile.v
  C:/Users/ahmed98/Desktop/MS3/MS3.srcs/sources_1/new/ctrlUnit.v
  C:/Users/ahmed98/Desktop/MS3/MS3.srcs/sources_1/new/CPU.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top CPU -part xc7a100tcsg324-1


write_checkpoint -force -noxdef CPU.dcp

catch { report_utilization -file CPU_utilization_synth.rpt -pb CPU_utilization_synth.pb }
